### ISSUE TITLE
So when I run the program, I keep encountering this error. Pls tell me how to fix this

### ISSUE THREAD

**Issue by kavinr24** [bassel27/Trading-Core#12]
====== WebDriver manager ======
Current google-chrome version is 123.0.6312
Get LATEST chromedriver version for 123.0.6312 google-chrome
Traceback (most recent call last):
  File "c:\Users\Kavin\Desktop\investopedia\Investopedia-Bot\main.py", line 11, in <module>
    frameAccAndCash(root)
  File "c:\Users\Kavin\Desktop\investopedia\Investopedia-Bot\tkinterFunctions.py", line 94, in frameAccAndCash
    scraping.openWebDriver()
  File "c:\Users\Kavin\Desktop\investopedia\Investopedia-Bot\Scraping.py", line 21, in openWebDriver
    ChromeDriverManager().install(), chrome_options=chromeOptions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\manager.py", line 19, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\driver_cache.py", line 74, in find_driver
    driver_version = driver.get_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\driver.py", line 39, in get_version
    self.get_latest_release_version()
  File "C:\Users\Kavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\driver.py", line 76, in get_latest_release_version
    validate_response(resp)
  File "C:\Users\Kavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\webdriver_manager\utils.py", line 90, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_123.0.6312
PS C:\Users\Kavin\Desktop\investopedia\Investopedia-Bot>

**Comment by Dullab635** [comment]
Hey man I’m facing the same issue did you find a fix?

**Comment by golfcart9** [comment]
> Hey man I’m facing the same issue did you find a fix?

I never found a fix but I just decided to create my own bot (not a very good one). There are some investopedia apis on github that you can try and make your own bot with.

**Comment by kavinr24** [comment]
> Hey man I’m facing the same issue did you find a fix?

I never found a fix but I just decided to create my own bot (not a very good one). There are some investopedia apis on github that you can try and make your own bot with.
