### ISSUE TITLE
_tkinter.TclError: error reading bitmap file "money_icon_lin.xbm

### ISSUE THREAD

**Issue by MydikFelof** [bassel27/Trading-Core#8]
My understanding of python is _extremely_ basic. I'm trying to run this on replit.com, so I could having it running while my laptop is off. Everytime I try to run it, I get the error below. 

_Traceback_ (most recent call last):
  File "main.py", line 9, in <module>
    frameInputAll (root)
  File "/home/runner/Investopedia-Bot/tkinterFunctions.py", line 101, in frameInputAll
    intro(root)
  File "/home/runner/Investopedia-Bot/tkinterFunctions.py", line 30, in intro
    root.iconbitmap(r'@money_icon_lin.xbm')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: error reading bitmap file "money_icon_lin.xbm"

**Comment by MydikFelof** [comment]
I just tried running it directly in powershell to see if replit was the problem. Got the same error, just with a .ico file instead of .xbm

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    frameInputAll (root)
  File "C:\Users\mdapa\Downloads\Investopedia-Bot-master\tkinterFunctions.py", line 101, in frameInputAll
    intro(root)
  File "C:\Users\mdapa\Downloads\Investopedia-Bot-master\tkinterFunctions.py", line 32, in intro
    root.iconbitmap(r'money_icon_win.ico')
  File "C:\Users\mdapa\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "money_icon_win.ico" not defined

**Comment by bassel27** [comment]
I don't know what's the problem here and why it appears to you. I tried the program on both Linux and Windows and it worked perfectly fine. Maybe try to remove lines **29-32** in `tkinterFunctions.py` and see if it works. This will remove the icon of the program which is the cause of your error; however, it won't affect the program. Try to remove these lines and keep me updated!

**Comment by MydikFelof** [comment]
Thanks for the suggestion. I tried that but got a new error this time. Again I tried it both on replit and powershell. I think it might be because I use firefox instead of chrome. I'm going to install chrome and try again. Here's the error anyway.

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    frameAccAndCash(root)
  File "C:\Users\mdapa\Downloads\Investopedia-Bot-master\tkinterFunctions.py", line 86, in frameAccAndCash
    scraping.openWebDriver()
  File "C:\Users\mdapa\Downloads\Investopedia-Bot-master\Scraping.py", line 19, in openWebDriver
    chromeOptions.add_extension('extension_1_41_2_0.crx')
  File "C:\Users\mdapa\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chromium\options.py", line 101, in add_extension
    raise IOError("Path to the extension doesn't exist")
OSError: Path to the extension doesn't exist

**Comment by bassel27** [comment]
I figured out what was wrong and fixed it in the latest commits. Fork the new repo and both of your two errors won't occur.

**Comment by bassel27** [comment]
Please bear in mind that I started this project one year ago and some of its functions don't work anymore due to changes in Investopedia's website. 
It just needs some minor code changes.

**Comment by bassel27** [comment]
This issue's been closed with the latest commit "Uploaded new files"

**Comment by MydikFelof** [comment]
Thank you. It's working now!

**Comment by bassel27** [comment]
Glad to help! Hope you can add and fix some features in your fork.
